=== xatapult/xtpxlib-common/xsd/load-list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.xtpxlib.nl/ns/common"
  xmlns:xtlc="http://www.xtpxlib.nl/ns/common">

  <xs:element name="load-list">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element name="load-from-disk">
          <xs:complexType>
            <xs:attributeGroup ref="xtlc:ag-href"/>
            <xs:attributeGroup ref="xtlc:ag-load-flags"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="load-from-zip">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="entry">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:anyURI" use="required">
                    <xs:annotation>
                      <xs:documentation>Name of the entry in the zip as a relative filename.</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attributeGroup ref="xtlc:ag-href"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
      <xs:attributeGroup ref="xtlc:ag-load-flags"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="ag-href">
    <xs:attribute name="href" type="xs:anyURI" use="required">
      <xs:annotation>
        <xs:documentation>The URI of the file we want to process.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:attributeGroup name="ag-load-flags">
    <xs:attribute default="false" name="force-xdm" type="xs:boolean"/>
    <xs:attribute default="true" name="fail-on-error" type="xs:boolean"/>
  </xs:attributeGroup>
</xs:schema>

=== xatapult/xtpxlib-common/xpl3mod/load-list/test/load-list-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<load-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xtpxlib.nl/ns/common ../../../xsd/load-list.xsd"
  xmlns="http://www.xtpxlib.nl/ns/common" force-xdm="false" fail-on-error="false">

  <load-from-disk href="test-contents/binary/Untitled.json" force-xdm="true"/>
  
  <load-from-disk href="test-contents/test.xml" force-xdm="true"/>

  <load-from-disk href="test-contents/binary/non-xml-posing-as-xml.xml" force-xdm="true"/>
  
  <load-from-disk href="test-contents/xml-posing-as-non-xml.something" force-xdm="true"/>

  <load-from-disk href="test-contents/does-not-exist.xml" force-xdm="true"/>

  <load-from-zip href="file:/C:/Data/Erik/work/xatapult/xtpxlib-common/xpl3mod/load-list/test/test-contents.zip">
    <entry name="test-contents/test.xml"/>
  </load-from-zip>

</load-list>
