=== xatapult/xtpxlib-common/xsd/mimetypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"
  targetNamespace="http://www.xtpxlib.nl/ns/mimetypes" xmlns="http://www.xtpxlib.nl/ns/mimetypes">
  <xs:annotation>
    <xs:documentation>Schema for the mimetype association datafile. This list is in data/mimetypes-table.xml and is used by xslmod/mimetypes.mod.xsl.</xs:documentation>
  </xs:annotation>
  <xs:element name="mimetypes">
    <xs:annotation>
      <xs:documentation>Root element of the MIME types associaton list.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="mimetype">
          <xs:annotation>
            <xs:documentation>The mimetype-extension association. This does not have to be unique. The first occurence in document order is the default one.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:attribute name="type">
              <xs:annotation>
                <xs:documentation>The mimetype (e.g. image/jpeg)</xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:minLength value="1"/>
                  <xs:whiteSpace value="collapse"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="extension">
              <xs:annotation>
                <xs:documentation>The file extension in lowercase (no leading dot, e.g. jpg)</xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[a-z0-9]+"/>
                  <xs:minLength value="1"/>
                  <xs:whiteSpace value="collapse"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== xatapult/xtpxlib-common/data/mimetypes-table.xml
<?xml version="1.0" encoding="UTF-8"?>
<mimetypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.xtpxlib.nl/ns/mimetypes ../xsd/mimetypes.xsd" xmlns="http://www.xtpxlib.nl/ns/mimetypes">
  <!-- ================================================================== -->
  <!--* 
    Table used for transforming file extensions into a MIME type and vice versa. 
	-->
  <!-- ================================================================== -->
  <!---->
  <mimetype type="application/futuresplash" extension="spl"/>
  <mimetype type="application/hta" extension="hta"/>
  <mimetype type="application/mac-compactpro" extension="cpt"/>
  <mimetype type="application/mac-binhex40" extension="hqx"/>
  <mimetype type="application/mathematica" extension="nb"/>
  <mimetype type="application/msaccess" extension="mdb"/>
  <mimetype type="application/msword" extension="doc"/>
  <mimetype type="application/octet-stream" extension="bin"/>
  <mimetype type="application/pdf" extension="pdf"/>
  <mimetype type="application/postscript" extension="ps"/>
  <mimetype type="application/rtf" extension="rtf"/>
  <mimetype type="application/smil" extension="smi"/>
  <mimetype type="application/zip" extension="zip"/>
  <mimetype type="application/vnd.ms-excel" extension="xls"/>
  <mimetype type="application/vnd.ms-powerpoint" extension="ppt"/>
  <mimetype type="application/x-director" extension="dcr"/>
  <mimetype type="application/x-doom" extension="wad"/>
  <mimetype type="application/x-dvi" extension="dvi"/>
  <mimetype type="application/x-futuresplash" extension="spl"/>
  <mimetype type="application/x-gzip" extension="gz"/>
  <mimetype type="application/x-java-archive" extension="jar"/>
  <mimetype type="application/x-javascript" extension="js"/>
  <mimetype type="application/ogg" extension="ogg"/>
  <mimetype type="application/x-shockwave-flash" extension="swf"/>
  <mimetype type="application/x-stuffit" extension="sit"/>
  <mimetype type="application/x-tex" extension="tex"/>
  <mimetype type="audio/basic" extension="au"/>
  <mimetype type="audio/midi" extension="mid"/>
  <mimetype type="audio/mpeg" extension="mp3"/>
  <mimetype type="audio/mpegurl" extension="m3u"/>
  <mimetype type="audio/prs.sid" extension="sid"/>
  <mimetype type="audio/x-aiff" extension="aif"/>
  <mimetype type="audio/x-gsm" extension="gsm"/>
  <mimetype type="audio/x-mpegurl" extension="m3u"/>
  <mimetype type="audio/x-pn-realaudio-plugin" extension="rpm"/>
  <mimetype type="audio/x-pn-realaudio" extension="ra"/>
  <mimetype type="audio/x-realaudio" extension="ra"/>
  <mimetype type="audio/x-scpls" extension="pls"/>
  <mimetype type="audio/x-sd2" extension="sd2"/>
  <mimetype type="audio/x-wav" extension="wav"/>
  <mimetype type="image/bmp" extension="bmp"/>
  <mimetype type="image/gif" extension="gif"/>
  <mimetype type="image/ief" extension="ief"/>
  <mimetype type="image/jpeg" extension="jpg"/>
  <mimetype type="image/jpeg" extension="jpeg"/>
  <mimetype type="image/pcx" extension="pcx"/>
  <mimetype type="image/png" extension="png"/>
  <mimetype type="image/svg+xml" extension="svg"/>
  <mimetype type="image/tiff" extension="tif"/>
  <mimetype type="image/vnd.wap.wbmp" extension="wbmp"/>
  <mimetype type="image/x-cmu-raster" extension="ras"/>
  <mimetype type="image/x-coreldraw" extension="cdr"/>
  <mimetype type="image/x-coreldrawpattern" extension="pat"/>
  <mimetype type="image/x-coreldrawtemplate" extension="cdt"/>
  <mimetype type="image/x-corelphotopaint" extension="cpt"/>
  <mimetype type="image/x-djvu" extension="djv"/>
  <mimetype type="image/x-jg" extension="art"/>
  <mimetype type="image/x-jng" extension="jng"/>
  <mimetype type="image/x-photoshop" extension="psd"/>
  <mimetype type="image/x-portable-anymap" extension="pnm"/>
  <mimetype type="image/x-portable-bitmap" extension="pbm"/>
  <mimetype type="image/x-portable-graymap" extension="pgm"/>
  <mimetype type="image/x-portable-pixmap" extension="ppm"/>
  <mimetype type="image/x-rgb" extension="rgb"/>
  <mimetype type="image/x-xbitmap" extension="xbm"/>
  <mimetype type="image/x-xpixmap" extension="xpm"/>
  <mimetype type="image/x-xwindowdump" extension="xwd"/>
  <mimetype type="model/iges" extension="igs"/>
  <mimetype type="model/mesh" extension="msh"/>
  <mimetype type="model/vrml" extension="wrl"/>
  <mimetype type="text/comma-separated-values" extension="csv"/>
  <mimetype type="text/css" extension="css"/>
  <mimetype type="text/h323" extension="323"/>
  <mimetype type="text/html" extension="htm"/>
  <mimetype type="text/iuls" extension="uls"/>
  <mimetype type="text/mathml" extension="mml"/>
  <mimetype type="text/plain" extension="txt"/>
  <mimetype type="text/richtext" extension="rtx"/>
  <mimetype type="text/rtf" extension="rtf"/>
  <mimetype type="text/scriptlet" extension="sct"/>
  <mimetype type="text/tab-separated-values" extension="tsv"/>
  <mimetype type="text/xml" extension="xml"/>
  <mimetype type="video/dl" extension="dl"/>
  <mimetype type="video/fli" extension="fli"/>
  <mimetype type="video/gl" extension="gl"/>
  <mimetype type="video/mpeg" extension="mpg"/>
  <mimetype type="video/quicktime" extension="mov"/>
  <mimetype type="video/vnd.mpegurl" extension="mxu"/>
  <mimetype type="video/x-dv" extension="dif"/>
  <mimetype type="video/x-la-asf" extension="lsf"/>
  <mimetype type="video/x-mng" extension="mng"/>
  <mimetype type="video/x-ms-asf" extension="asf"/>
  <mimetype type="video/x-msvideo" extension="avi"/>
  <mimetype type="video/x-sgi-movie" extension="movie"/>
  <mimetype type="x-conference/x-cooltalk" extension="ice"/>
  <mimetype type="x-world/x-vrml" extension="vrm"/>
  <mimetype type="video/x-flv" extension="flv"/>
  <mimetype extension="docm" type="application/vnd.ms-word.document.macroEnabled.12"/>
  <mimetype extension="docx" type="application/vnd.openxmlformats-officedocument.wordprocessingml.document"/>
  <mimetype extension="dotx" type="application/vnd.openxmlformats-officedocument.wordprocessingml.template"/>
  <mimetype extension="potm" type="application/vnd.ms-powerpoint.template.macroEnabled.12"/>
  <mimetype extension="potx" type="application/vnd.openxmlformats-officedocument.presentationml.template"/>
  <mimetype extension="ppam" type="application/vnd.ms-powerpoint.addin.macroEnabled.12"/>
  <mimetype extension="ppsm" type="application/vnd.ms-powerpoint.slideshow.macroEnabled.12"/>
  <mimetype extension="ppsx" type="application/vnd.openxmlformats-officedocument.presentationml.slideshow"/>
  <mimetype extension="pptm" type="application/vnd.ms-powerpoint.presentation.macroEnabled.12"/>
  <mimetype extension="pptx" type="application/vnd.openxmlformats-officedocument.presentationml.presentation"/>
  <mimetype extension="xlam" type="application/vnd.ms-excel.addin.macroEnabled.12"/>
  <mimetype extension="xlsb" type="application/vnd.ms-excel.sheet.binary.macroEnabled.12"/>
  <mimetype extension="xlsm" type="application/vnd.ms-excel.sheet.macroEnabled.12"/>
  <mimetype extension="xlsx" type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>
  <mimetype extension="xltm" type="application/vnd.ms-excel.template.macroEnabled.12"/>
  <mimetype extension="xltx" type="application/vnd.openxmlformats-officedocument.spreadsheetml.template"/>
  <mimetype extension="epub" type="application/epub+zip"/>
</mimetypes>
