=== xatapult/xtpxlib-common/xsd/parameters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
  <xs:annotation>
    <xs:documentation>Schema for sets of parameters as used by this library. 

Use [parameters.mod.xsl](%parameters.mod.xsl) for turning these lists into maps. An explanation of the parameter mechanism can be found [here](%parameters-explanation).

Although this is schema for no namespace, parameters can be in *any* namespace (if you use [parameters.mod.xsl](%parameters.mod.xsl) for processing them).</xs:documentation>
  </xs:annotation>
  <xs:element name="parameters">
    <xs:annotation>
      <xs:documentation>Root element for a set of parameters (either in a document on its own or embedded).</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="g-parameter-group"/>
      </xs:sequence>
      <xs:anyAttribute namespace="##any"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="t-parameter-name">
    <xs:restriction base="xs:NCName"/>
  </xs:simpleType>
  <xs:group name="g-parameter">
    <xs:sequence>
      <xs:element name="parameter">
        <xs:annotation>
          <xs:documentation>A single parameter.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="value">
              <xs:annotation>
                <xs:documentation>Value(s) for this parameter.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:anyAttribute namespace="##any" processContents="skip">
                      <xs:annotation>
                        <xs:documentation>Attributes on a value can be used to filter values based on different circumstances (e.g. language, platform, etc.).</xs:documentation>
                      </xs:annotation>
                    </xs:anyAttribute>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="name" type="t-parameter-name" use="required">
            <xs:annotation>
              <xs:documentation>Name of the parameter.</xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:anyAttribute namespace="##any"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
  <xs:group name="g-parameter-group">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:group ref="g-parameter"/>
        <xs:element name="group">
          <xs:complexType>
            <xs:group ref="g-parameter-group"/>
            <xs:attribute name="name" type="t-parameter-name" use="required">
              <xs:annotation>
                <xs:documentation>Name of the parameter.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:anyAttribute namespace="##any"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:sequence>
  </xs:group>
</xs:schema>

=== xatapult/xtpxlib-common/doc/data/componentdoc-global-parameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<parameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../../xtpxlib-common/xsd/parameters.xsd">
  <!-- ================================================================== -->
  <!--~
    TBD
  -->
  <!-- ================================================================== -->
  
  <parameter name="owner-company-name">
    <value>Xatapult&#160;Content&#160;Engineering</value>
  </parameter>
  
  <parameter name="owner-company-website">
    <value>http://www.xatapult.com</value>
  </parameter>
  
   <parameter name="owner-company-phone">
    <value>+31&#160;6&#160;53260792</value>
  </parameter>
  
  <parameter name="owner-company-github">
    <value>https://github.com/xatapult</value>
  </parameter>
  
  <parameter name="author-name">
    <value>Erik&#160;Siegel</value>
  </parameter>
  
  <parameter name="author-email-address">
    <value>erik@xatapult.com</value>
  </parameter>
  
  <parameter name="library-name">
    <value>xtpxlib</value>
  </parameter>
  
  <parameter name="core-component-name">
    <value>xtpxlib-common</value>
  </parameter>

</parameters>
